---
title: "Nuclear generated what percent of clean energy in 2017?"
output: html_notebook
---

# Data from U.S. EIA
https://www.eia.gov/electricity/data.php

Choose "Generation and Thermal Output", then under "Detailed preliminary EIA-923 monthly and annual survey data (back to 1990)", and "State-level generation and fuel consumption data", download "Annual (back to 1990)"

```{r}
annual_state_electricity <- read_excel("electricity_data.xls", skip = 2)


#make as tibble, clean for readability
annual_state_electricity <- as.tbl(annual_state_electricity)
annual_state_electricity <- annual_state_electricity %>% mutate(Source = recode(Source, 'Wood and Wood Derived Fuels'='Wood Derived Fuels')) %>% mutate(Source = recode(Source, 'Hydroelectric Conventional'='Hydroelectric')) %>% mutate(Source = recode(Source, 'Solar Thermal and Photovoltaic'='Solar Thermal and PV')) 

# Only using total electric power industry, in 2017
total_industry_2017 <- annual_state_electricity %>% filter(Type == "Total Electric Power Industry") %>% filter(Year == 2017) %>%
  filter(Source != "Total")

#clean energy summed over all states in 2017
clean_all_states_2017 <- total_industry_2017 %>% filter(Source %in% c("Geothermal", "Hydroelectric", "Nuclear", "Solar Thermal and PV", "Other Biomass", "Wind", "Wood Derived Fuels" )) %>% summarise(total_clean = sum(Gen))

#nuclear energy summed over all states in 2017
nuclear_all_states_2017 <- total_industry_2017 %>% filter(Source == "Nuclear") %>% summarise(total_nuclear = sum(Gen))

#percent
nuclear_percent_of_clean_energy <- (nuclear_all_states_2017$total_nuclear / clean_all_states_2017$total_clean) * 100

```

```{r}

paste0("In 2017, nuclear power generated ", round(nuclear_percent_of_clean_energy,2), "% of the U.S. clean energy")

```